package dystsys.ca.professional_hub.gui;

import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.SwingUtilities;

import com.generated.workshop.grpc.CheckInWorkerReq;
import com.generated.workshop.grpc.CheckInWorkerRes;

import dystsys.ca.professional_hub.clients.ProfessionalHubClient;

public class ProfessionalHubGUI extends JFrame {
	private static final long serialVersionUID = 1L;

	// central client
	private ProfessionalHubClient hubClient;

	// GUI components
	private JTabbedPane tabbedPane;
	private JTextPane resultPane;

	// Workshop tab fields
	private JTextField workerIdField;
	private JTextField workshopIdField;
	private JButton checkInButton;

	public ProfessionalHubGUI() {
		hubClient = new ProfessionalHubClient();

		setTitle("Professional Hub");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setSize(1100, 720);
		setLocationRelativeTo(null);

		JTabbedPane tabbedPane = new JTabbedPane(JTabbedPane.TOP);
		getContentPane().add(tabbedPane, BorderLayout.NORTH);

		JPanel Workshop = new JPanel();
		tabbedPane.addTab("Workshop", null, Workshop, null);

		JLabel lblNewLabel = new JLabel("Worker ID");
		Workshop.add(lblNewLabel);

		workerIdField = new JTextField();
		Workshop.add(workerIdField);
		workerIdField.setColumns(10);

		JLabel lblNewLabel_1 = new JLabel("Workshop ID");
		Workshop.add(lblNewLabel_1);

		workshopIdField = new JTextField();
		Workshop.add(workshopIdField);
		workshopIdField.setColumns(10);

		JButton checkInButton = new JButton("Check In Worker");
		Workshop.add(checkInButton);

		JPanel Productivity = new JPanel();
		tabbedPane.addTab("Productivity", null, Productivity, null);

		JPanel Guardian = new JPanel();
		tabbedPane.addTab("Guardian", null, Guardian, null);

		JScrollPane scrollPane = new JScrollPane();
		getContentPane().add(scrollPane, BorderLayout.SOUTH);

		JTextPane resultPane = new JTextPane();
		resultPane.setFont(new Font("Tahoma", Font.BOLD, 18));
		resultPane.setText("Professional Hub Controller");
		getContentPane().add(resultPane, BorderLayout.WEST);

		initComponents(); // generated by WindowBuilder (ECLIPSE plugin)

		// shutdown hook
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosing(WindowEvent e) {
				hubClient.shutdown();
			}
		});
	}

	private void initComponents() {
		tabbedPane = new JTabbedPane();
		resultPane = new JTextPane();

		// Workshop tab components
		JLabel lblWorkerId = new JLabel("Worker ID");
		workerIdField = new JTextField(15);
		JLabel lblWorkshopId = new JLabel("Workshop ID");
		workshopIdField = new JTextField(15);
		checkInButton = new JButton("Check In Worker");

		JPanel workshopPanel = new JPanel();
		
		JLabel lblNewLabel_2 = new JLabel("Worker ID: W-1001 | Workshop ID: WS-001");
		workshopPanel.add(lblNewLabel_2);
		workshopPanel.add(lblWorkerId);
		workshopPanel.add(workerIdField);
		workshopPanel.add(lblWorkshopId);
		workshopPanel.add(workshopIdField);
		workshopPanel.add(checkInButton);

		tabbedPane.addTab("Workshop", workshopPanel);
		tabbedPane.addTab("Productivity", new JPanel());
		tabbedPane.addTab("Guardian", new JPanel());

		// Bottom result pane
		resultPane.setEditable(false);
		JScrollPane scrollPane = new JScrollPane(resultPane);

		// this allows user to resize the result area
		JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, tabbedPane, scrollPane);
		splitPane.setResizeWeight(0.75);
		splitPane.setDividerLocation(450);

		// main layout
		getContentPane().setLayout(new BorderLayout());
		getContentPane().add(splitPane, BorderLayout.CENTER);

		// unary checkInWorker
		checkInButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent event) {
				checkInWorkerButtonActionPerformed(event);
			}
		});
	}

	public ProfessionalHubClient getHubClient() {
		return hubClient;
	}

	// main launcher
	public static void main(String[] args) {
		SwingUtilities.invokeLater(() -> {
			new ProfessionalHubGUI().setVisible(true);
		});
	} // main

	private void checkInWorkerButtonActionPerformed(ActionEvent evt) {
		String workerId = workerIdField.getText().trim();
		String workshopId = workshopIdField.getText().trim();

		// check empty field
		if (workerId.isEmpty() || workshopId.isEmpty()) {
			resultPane.setText("Please fill in both fields!\n" + resultPane.getText());
			return;
		}

		// gRPC request
		CheckInWorkerReq req = CheckInWorkerReq.newBuilder().setWorkerId(workerId).setWorkshopId(workshopId).build();

		try {
			CheckInWorkerRes res = getHubClient().getWorkshopBlockingStub().checkInWorker(req);

			String message = String.format("Worker %s checked in successfully!%nModule: %s%nCredits: %d%n%n", workerId,
					res.getModuleName(), res.getWorkshopCredits());

			resultPane.setText(message + resultPane.getText());
		} catch (Exception e) {
			resultPane.setText("Error: " + e.getMessage() + "\n" + resultPane.getText());
		}
	}
} // ProfessionalHubGUI
